version: '3'
services:
  php:
    container_name: php-intshop
    domainname: php
    hostname: php
    image: php:7.2-fpm
    working_dir: "/var/www/app"
    volumes:
      - "./src:/var/www/app"
      - "./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf"
      - "./docker/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf"
      - "./docker/php/php.ini:/usr/local/etc/php/php.ini"
    tty: true
  nginx:
    container_name: nginx-intshop
    domainname: nginx
    hostname: nginx
    image: nginx:1.13
    volumes:
      - "./src:/var/www/app"
      - "./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 1234:80
    links:
      - "php"